
conversations:
- - hello
  - chào bạn, tôi có thể giúp gì cho bạn.
- - hi robot
  - chào bạn, tôi có thể giúp gì cho bạn.
- - hai robot
  - chào bạn, tôi có thể giúp gì cho bạn.
- - greetings!
  - chào bạn, tôi có thể giúp gì cho bạn.
- - xin chào
  - chào bạn, tôi có thể giúp gì cho bạn.
- - địa chỉ công ty
  - dia_chi_cong_ty_mkac
- - địa chỉ công ty ở đâu
  - dia_chi_cong_ty_mkac
- - công ty ở đâu
  - dia_chi_cong_ty_mkac
- - địa chỉ công ty meiko
  - dia_chi_cong_ty_mkac
- - công ty meiko automation ở đâu
  - dia_chi_cong_ty_mkac
- - địa chỉ công ty mkac
  - dia_chi_cong_ty_mkac
- - mật khẩu wifi
  - mat_khau_wifi
- - mật khẩu wifi là gì
  - mat_khau_wifi
- - cho xin mật khẩu wifi
  - mat_khau_wifi

- - công ty mkac
  - cong_ty_mkac
- - công ty meiko automation
  - cong_ty_mkac
- - giới thiệu về công ty
  - cong_ty_mkac
- - giới thiệu về công ty mkac
  - cong_ty_mkac
- - giới thiệu về công ty meiko automation
  - cong_ty_mkac
- - biết gì về công ty mkac
  - cong_ty_mkac
- - biết gì về công ty meiko automation
  - cong_ty_mkac
- - bạn biết gì về công ty mkac
  - cong_ty_mkac
- - bạn biết gì về công ty meiko automation
  - cong_ty_mkac
- - công ty mkac là gì
  - cong_ty_mkac
- - công ty meiko automation là gì
  - cong_ty_mkac

- - công ty mkac làm gì
  - linh_vuc_cong_ty_mkac
- - công ty meiko automation làm gì
  - linh_vuc_cong_ty_mkac
- - công ty mkac hoạt động trong lĩnh vực nào
  - linh_vuc_cong_ty_mkac
- - công ty meiko automation hoạt động trong lĩnh vực nào
  - linh_vuc_cong_ty_mkac
- - lĩnh vực hoạt động của công ty mkac là gì
  - linh_vuc_cong_ty_mkac
- - lĩnh vực hoạt động của công ty meiko automation là gì
  - linh_vuc_cong_ty_mkac
- - giới thiệu về lĩnh vực hoạt động của công ty mkac
  - linh_vuc_cong_ty_mkac
- - giới thiệu về  lĩnh vực hoạt động của công ty meiko automation
  - linh_vuc_cong_ty_mkac

- - tập đoàn meiko
  - tap_doan_meiko
- - giới thiệu về tập đoàn meiko
  - tap_doan_meiko
- - lịch sử tập đoàn meiko
  - tap_doan_meiko
- - biết gì về tập đoàn meiko
  - tap_doan_meiko
- - bạn biết gì về tập đoàn meiko
  - tap_doan_meiko
- - tập đoàn meiko làm gì
  - tap_doan_meiko